### ISSUE TITLE
Windows and NUT CGI Web Pages

### ISSUE THREAD

**Issue by aarnold-sd68** [networkupstools/nut#3219]
I'm taking a look at the web interface for Nut, Nut-cgi I believe it's called, but I'm not having any luck :(.  Is it even possible to get it working on windows?  I can get the main page working, Network UPS Tools with the statistics and settings links.  But clicking the links gets me a page not found error.  If I run https://serverip/cgi-bin/upsstats.cgi.exe I get this error :Error: can't open template file (upsstats.html) upsstats: Can't open 
\\?\C:\mingw64\cgi-bin\..\etc/upsstats.html: Invalid argument.  Which I'm assuming has something to do with it :).  The file does exist in etc directory but that is a weird way of displaying the path.  If I type in the path to the upstats.html file I do get the page all be it with no data, which I believe makes sense as it needs to come from the upstats.cgi.exe.    If I add ?json to the end I do get some data.  

oh and I also uncommented the "I_HAVE_SECURED_MY_CGI_DIRECTORY" in upsset.conf

**Comment by jimklimov** [comment]
yeah, the path looks weird; there probably should be a separator between `cgi-bin/..` at least

Maybe there's a need to tweak code and provide a PR to address this... I am not aware of anyone running this yet, and the Windows port has certain known incomplete bits, so there may well be unknown ones too.

BTW it would be helpful for a repro case to post how you managed to get this far :)

**Comment by aarnold-sd68** [comment]
In IIS I set the root to install for default website to c:\mingw64\.  This then gives me access to to cgi-bin and etc and all the other directories.  I had to enable cgi-exe as this is disabled by default in iis.  I updated the hosts.conf,upsset.conf and renamed upsstats.html.sample and upsstates-single.html.sample to not include the sample.  My URL is https://servername/cgi-bin/upsstats.cgi.exe?json which gives me some data, but doesn't give me the pretty template view.  if I go to https://servername/html I get the start page with statistics and settings but the links don't work when you click them :(.  https://servername/cgi-bin/upsstats.cgi.exe gives me the error : Error: can't open template file (upsstats.html) upsstats: Can't open \\?\c:\mingw64\cgi-bin\..\etc/upsstats.html: Invalid argument.  Loading : https://servername/cgi-bin/upsset.cgi.exe gives me this error Error: Can't open upsset.conf to verify security settings.. I've enabled Basic and windows auth and disabled anonymous, this was done to secure the server a little bit, might do more later.  

IIS extra features that I installed as I went needs review to make sure are needed : Web-Windows-Auth,Web-Net-Ext45,Web-ASP,Web-CGI,Web-ISAPI-Ext,Web-ISAPI-Filter,Web-Filtering
IIS already had : Web-Common-Http,Web-Dir-Browsing,Web-Http-Errors,Web-Static-Content,Web-Http-Logging,Web-Log-Libraries

I think that's all the information that I have so far.  It's seems like it's SO close to working.  

I'm assuming this is all related to the same pathing issue, I don't think it's a permissions issue as I can run the individual components and they seem to sort of work.  I'm also not sure this is really how it should be setup, it seems a little unsecure to have IIS have access to the entire NUT folders.  I think a better way might be to point it at html dir and have virtual dirs to etc and cgi-bin.  But I'm not sure if thats workable with how linux/unix system do things,  or have it completely separated into it's own folder(s) that can be dropped in to c:\inetpub\wwwroot <- I'm sure you know this but this is the default IIS default site directory.

**Comment by jimklimov** [comment]
>have it completely separated into it's own folder(s) that can be dropped 

Probably you can copy over the `cgi-bin` directory (it includes the libraries needed by those executables) and perhaps the `html` directory near it. If IIS can pass down environment variables into CGI programs, `NUT_CONFPATH` can be used to point to the `etc` located out of web-server scope.

**Comment by jimklimov** [comment]
PR #3224 with hopefully a fix for the relative path situation (lack of slash between `cgi-bin` dir name and `..\etc`) was merged to master. Testing that the result works is still desirable :)

**Comment by aarnold-sd68** [comment]
hmm..  not sure if I should put this here or create a new ticket, but I just tried 3855 and 3860  and neither of them load, nut.exe -N for clarification.  But 3840 does, I had a copy of it so I gave it a shot.  I think next I'll try 3852 and see if it loads.  
I don't get any error message that I can find so far it just doesn't do anything :(.  In debug mode I got a starting message but that was it.  

* I can confirm that 3852 is the last version that seems to load, after that nothing seems to load.  It seems to be having trouble finding some dlls, mingw64\libexec.  This doesn't entirely fix it but it at least starts now, still doesn't work :(.

**Comment by jimklimov** [comment]
I'll check if I can get some Win VM to spin up to test this...

**Comment by jimklimov** [comment]
Huh, recent 7z "tarballs" built by appveyor are 13Mb starting from [NUT-for-Windows-x86_64-SNAPSHOT-2.8.4.3859-master.7z](https://ci.appveyor.com/api/buildjobs/4xv53fmhv69wcmnw/artifacts/NUT-for-Windows-x86_64-SNAPSHOT-2.8.4.3859-master.7z) at https://ci.appveyor.com/project/nut-travis/nut/builds/53259933/artifacts - need to investigate what disappeared (or compressed so well?)

The preceding master-branch build [NUT-for-Windows-x86_64-SNAPSHOT-2.8.4.3858-master.7z](https://ci.appveyor.com/api/buildjobs/dux97s4xvp601xpg/artifacts/NUT-for-Windows-x86_64-SNAPSHOT-2.8.4.3858-master.7z) at https://ci.appveyor.com/project/nut-travis/nut/builds/53259931/artifacts was 52Mb... but still, this is newer than 3855 which already did not work for you.

> * [Merge pull request #3222 from jimklimov/issue-2288](https://ci.appveyor.com/project/nut-travis/nut/builds/53259933)
[2.8.4.3859-master](https://ci.appveyor.com/project/nut-travis/nut/builds/53259933) - #3222
>   5 days ago by [Jim Klimov](https://github.com/jimklimov) (committed by [GitHub](https://github.com/web-flow))
master [e439012c](https://github.com/networkupstools/nut/commit/e439012cd99ce949872dbcef24dc7bf145fb7f25)
>   5 days ago in 55 min 3 sec
> * [Merge pull request #3221 from jimklimov/issue-3055](https://ci.appveyor.com/project/nut-travis/nut/builds/53259931)
[2.8.4.3858-master](https://ci.appveyor.com/project/nut-travis/nut/builds/53259931) - #3221
>   5 days ago by [Jim Klimov](https://github.com/jimklimov) (committed by [GitHub](https://github.com/web-flow))
master [adce2c00](https://github.com/networkupstools/nut/commit/adce2c003ec2f57b6f86b03d098eccea5bcad45f)
>   5 days ago in 53 min 30 sec

(It is a separately logged issue to investigate why those binaries are so huge and what can be done to trim them down; it seems to be a multi-platform problem though, maybe something about modern compilers and/or possible benefits of using private shared libraries instead of binaries that each carry a copy of common-code baggage?..)

Hm, actually looking at https://ci.appveyor.com/project/nut-travis/nut/history -

The previous mentioned build of master-branch targeted builds, "3855" at https://ci.appveyor.com/project/nut-travis/nut/builds/53257330/artifacts was the last build for "Pull request #3224" (and its archive is 52Mb in size):

> * [Pull request #3224 - Fix numerous issues with path resolution in NUT for Windows builds](https://github.com/networkupstools/nut/pull/3224)
[common/common.c, include/common.h, scripts/Windows/wininit.c, server/upsd.c, drivers/upsdrvctl.c: refactor with a getfullpath2() to mix configure script options and hard-coded fallbacks [#3207]](https://ci.appveyor.com/project/nut-travis/nut/builds/53257330)
>   [2.8.4.3855-master](https://ci.appveyor.com/project/nut-travis/nut/builds/53257330)
>   6 days ago by [Jim Klimov](https://github.com/jimklimov) master [b80566e6](https://github.com/networkupstools/nut/commit/b80566e6217910208cf21376a27aab271919f308) ← [issue-3207](https://github.com/jimklimov/nut/tree/issue-3207) [f95c89b4](https://github.com/jimklimov/nut/commit/f95c89b4567e28533a27146c92de45ace7c6777d)
>   6 days ago in 49 min 58 sec

Build "3857" was where PR #3224 for the Windows paths issue was merged: 
> * [Merge pull request #3224 from jimklimov/issue-3207](https://ci.appveyor.com/project/nut-travis/nut/builds/53259930)
[2.8.4.3857-master](https://ci.appveyor.com/project/nut-travis/nut/builds/53259930)
>   5 days ago by [Jim Klimov](https://github.com/jimklimov) (committed by [GitHub](https://github.com/web-flow))
master [26b8e730](https://github.com/networkupstools/nut/commit/26b8e7305cacbc54cb1c6bf84814315bc51521a1)
>   Failed (timeout) 5 days ago in 1 hr

Build "3852" was for another PR targeting the master branch (so not including path changes yet):
> * [Pull request #3223 - Avoid rebuilding `nut_version.h` within one stack of (parallel) `make` processes](https://github.com/networkupstools/nut/pull/3223)
>   [Makefile.am: all-fanout-maybe: report when optimized build is finished and we hand off to "make all" default implementation (may regenerate headers again) [#3039]](https://ci.appveyor.com/project/nut-travis/nut/builds/53254924)
[2.8.4.3852-master](https://ci.appveyor.com/project/nut-travis/nut/builds/53254924)
>   6 days ago by [Jim Klimov](https://github.com/jimklimov) master [17639a6f](https://github.com/networkupstools/nut/commit/17639a6fcc8f77bb66c3471fb4a3fadabd23cd96) ← [issue-3039](https://github.com/jimklimov/nut/tree/issue-3039) [f465e9ce](https://github.com/jimklimov/nut/commit/f465e9ce0e88a05535326e8090ed78cec22239cb)
>   6 days ago in 45 min 8 sec

Build "3860" was for a different branch/PR, even not targeting the master branch, and possibly did not include these changes yet. Might have, though, as it was a re-merge from master after a bunch of PRs were merged into master:
> * [Pull request #3225 - FTY remerge from master as of 2025-12-18](https://github.com/networkupstools/nut/pull/3225)
[Merge remote-tracking branch 'upstream/master' into FTY as of 2025-12-18](https://ci.appveyor.com/project/nut-travis/nut/builds/53260504)
>   [2.8.4.3860-FTY](https://ci.appveyor.com/project/nut-travis/nut/builds/53260504)
>   5 days ago by [Jim Klimov](https://github.com/jimklimov)
[FTY](https://github.com/networkupstools/nut/tree/FTY) [4264592b](https://github.com/networkupstools/nut/commit/4264592b05a3236382c73c71029f026bf6bb8b12) ← [FTY-remerge-20251220](https://github.com/jimklimov/nut/tree/FTY-remerge-20251220) [f874ce42](https://github.com/jimklimov/nut/commit/f874ce4285417c1165d642aac8cbdb460e92e220)
>   5 days ago in 55 min 35 sec

**Comment by jimklimov** [comment]
So, the size difference is that for some reason (probably related to fixes for portable scripting) copies/links of the third-party libraries no longer got bundled near the NUT `*.exe` and `*.dll` files that use them, which is the most convenient way in Windows to get shared objects to be loaded into the program. So this matches the problem you saw as "It seems to be having trouble finding some dlls".

Thanks for the quick heads-up, this is indeed something to fix before a release, whenever that happens :D

**Comment by jimklimov** [comment]
So... explaining it took a lot longer than finding the typo, now that I had an idea what to look out for :D

**Comment by jimklimov** [comment]
Hopefully this will work (should be built in a couple of hours - check in https://ci.appveyor.com/project/nut-travis/nut/builds/53282017/artifacts):

> * [Makefile.am: install-win-bundle-thirdparty: typo fix (broken DLL delivery) [fallout of PR #3222, issue #3219]](https://ci.appveyor.com/project/nut-travis/nut/builds/53282017)
[2.8.4.3879-master](https://ci.appveyor.com/project/nut-travis/nut/builds/53282017)
>   a few seconds ago by [Jim Klimov](https://github.com/jimklimov)
>   [master](https://github.com/networkupstools/nut/tree/master) [fe3a9aee](https://github.com/networkupstools/nut/commit/fe3a9aee40e5278855a901d83dec821855a5ff7d)
>   Queued

Or if something times out again, a later Appveyor CI iteration (after build "3879").

* UPDATE: It is here and big again: https://ci.appveyor.com/api/buildjobs/uw4q5ut2yj3g656s/artifacts/NUT-for-Windows-x86_64-SNAPSHOT-2.8.4.3879-master.7z

**Comment by jimklimov** [comment]
More issues found in that iteration, now looking forward to https://ci.appveyor.com/project/nut-travis/nut/builds/53287296

**Comment by jimklimov** [comment]
Experimenting on a VM now. There are strange issues around `LISTEN *` in `upsd.conf`, where one file descriptor (of IPv4+IPv6 shim) apparently does not open and `upsd` `mainloop()` goes crazy. Any amount of specific `LISTEN` directives, including those with same set of IP addresses and ports as auto-shimmed for `*`, works.

Otherwise the code in PR #3235 seems to work. Sort of. Does not seem to revive individual processes if I kill them, for example (service stop/start does work). Guess this area needs a lot of work still to be less fragile, but basically works. Started me the daemons and drivers, a dummy did pass through info from the real server.

**Comment by jimklimov** [comment]
@aarnold-sd68 : a number of follow-up PRs were merged that should improve the situation on Windows, please give them a try when Appveyor is done with master-branch builds of today :)

**Comment by aarnold-sd68** [comment]
Sorry for the long deloy, was on holidays.  But the newer builds seem to load now :D.  Will now continue my testing.  Thank you for fixing this so quickly.  Version 2.8.4.2923 is the version that I tested.

**Comment by aarnold-sd68** [comment]
things are working MUCH better now for webpage loading.  But unfortunately not 100%.   Now when I get presented with a login page :).  The initial pages goes to : https://{servername}/cgi-bin/upsset.cgi.exe, but when I click login it goes to : https://{ServerName}/cgi-bin/upsset.cgi.  If I go to https://{Servername}/cgi-bin/upsstats.cgi.exe I'm getting data and even the correct data :D.  I'm assuming here that it's something in the template or the what ever generates the links that needs to have the .exe added when running on windows.  

There is also a small error in the template, well what I'm assuming is the template.  But this is major progress thank you for fixing the errors and make it work at all with windows.  

<img width="326" height="49" alt="Image" src="https://github.com/user-attachments/assets/325ab3c1-d6d9-4280-95a7-91e996c5f512" />

**Comment by jimklimov** [comment]
cool, thanks for the update

**Comment by jimklimov** [comment]
Found a few more impurities in the code, and updated the docs following your notes above and my experiments -- another PR brewing...

However at the moment I am stumbled with the CGI programs not finding their `*.conf` and template files when running in the IIS web server, while they do find them when I execute via command line.

**Comment by jimklimov** [comment]
As I did not see it fully running yet, not sure what's up with the template. One educated guess could be CR vs CRLF line ending mismatch (one maybe in coded expectations, and other in platform-specific `printf` and/or git-derived files)?..

**Comment by aarnold-sd68** [comment]
I think the "not finding their *.conf and template files" has been fixed, as the pages are now loading when manually entered.  It currently is not linking properly when you click any links on any of the pages, you can test this by editing the browser link and entering in the various pages.  The links don't go to .exe they just go to .cgi which for windows don't exist.  This also affect the icon creation I believe, sorry if I wasn't clear, this was all test with version : 2.8.4.2923.   
For setup, I pointed IIS's default directory at the root of NUT and then I could go to /cgi-bin/upsstats.cgi.exe.  I also enabled exe support in IIS (Would need to look up the instructions again, not an IIS admin, but I can pretend to be one ), with windows/basic authentication enabled (this isn't needed for testing but probably is for production).    
As for the error in the "template" that is a very minor cosmetic issue, their are bigger fish to fry as they say :D.

**Comment by jimklimov** [comment]
@aarnold-sd68 : got a new round of improvements to try when #3249 gets built. At this time there is a known problem with `upsset.cgi(.exe)` never finishing the read of incoming POST query data. But I did get its initial login page, as well as tables and graphs from `upsstats` and `upsimage` programs, so at least there's something definitely better now :)

**Comment by jimklimov** [comment]
@aarnold-sd68 : it was a bumpy ride in that PR #3249 but can you please check https://ci.appveyor.com/api/buildjobs/n58ibyyxyykox2d6/artifacts/NUT-for-Windows-x86_64-SNAPSHOT-2.8.4.3933-master.7z if all about CGI behaves well (and the updated doc, see new IIS chapter in https://github.com/jimklimov/nut/blob/issue-3207/docs/man/upsset.conf.txt file)?

"Worked for me" with Windows 10, IIS for table/graph lookups and for `upsset` changes of run-time driver debug level (something least intrusive and easy to see).

UPDATE: Or better yet, test https://ci.appveyor.com/project/nut-travis/nut/builds/53342669/artifacts when that completes 2.8.4.3938-master

**Comment by aarnold-sd68** [comment]
with 2.8.4.3933 almost everything is working.  For some reason two of the UPS don't have names, they did before.  I'll test with 3938 to see if that fixes it but so far I'm liking the major improvements that have happened in such a short time.  Thank you for looking after all this and getting it working.  Same issues with 2.8.4.3938.



<img width="929" height="237" alt="Image" src="https://github.com/user-attachments/assets/12b94885-b236-43c9-9562-2d3b57ea3ded" />

**Comment by jimklimov** [comment]
The backslash instead of version on top of the page was an interim bug, I think fixed in latest build. Did you regenerate and install the `upsstats*.html(.sample)` template files?

I wonder if the problem is in C code or in (possibly outdated) template?

I tested with one UPS, will try ton= add a few dummies.

**Comment by aarnold-sd68** [comment]
Updated to build 2.8.4.2938 and the \ is gone, but the two other UPS still don't show properly :(. haven't tried build 2.8.4.2939 as it appears to have failed to generate files.  

<img width="942" height="288" alt="Image" src="https://github.com/user-attachments/assets/f3ccd344-c52e-4ffe-812c-84fe7123bf48" />

**Comment by jimklimov** [comment]
Thanks, that gift well just never stops giving :}

**Comment by jimklimov** [comment]
Confirmed with an added dummy monitor line. Also the table header looks puzzling - one UPS description in your case, error in mine - seems to be info about the last UPS in table?

<img width="846" height="214" alt="Image" src="https://github.com/user-attachments/assets/1b81c5c5-ff87-4f9b-9ba8-f941988013fb" />

**Comment by jimklimov** [comment]
Aha, so the table markup is mangled in HTML, and that "header" is not such, but a runaway table cell (probably "model").

**Comment by jimklimov** [comment]
That broken table was a fun one, also boiled down to a Windows nuance as a platform. Opening the template file as a binary (not text) stream helped. One byte of change and a morning of debug to find it :D

Now waiting for https://ci.appveyor.com/project/nut-travis/nut/builds/53351410 to yield artifacts for you to test :)

Note that since https://ci.appveyor.com/project/nut-travis/nut/builds/53351547 with a fix for #3252 you would also need to update the HTML template files to start with a `@NUT_UPSSTATS_TEMPLATE@` line.

**Comment by aarnold-sd68** [comment]
I've noticed there has been a lot of changes over the weekend.  Should I be testing with the links provided, or maybe version 2.8.4.3946-master, or the latest which seems like it's even more of an experiment then the current windows builds :D.

**Comment by jimklimov** [comment]
Until that PR is merged, keep an eye out for builds of that branch; others would not include the CGI oriented changes yet.

**Comment by aarnold-sd68** [comment]
So anything with Pull request #3249?  How can I tell if it's merged? Will it say in this bug report?

Oh it's the part here that shows me the branch :) : 

<img width="325" height="40" alt="Image" src="https://github.com/user-attachments/assets/b8ccd7fc-3579-4764-8303-de7b3839206e" />

**Comment by aarnold-sd68** [comment]
That looks way better Thank you..

<img width="1068" height="380" alt="Image" src="https://github.com/user-attachments/assets/e2cfd4de-8145-4bb1-b618-e77c2432b722" />

**Comment by jimklimov** [comment]
Yeah, PR page will get a purple status highlight when merged (same for issue page when one is resolved).

**Comment by jimklimov** [comment]
Other highlights of that PR include:
* links to JSON representations of single or multiple device data
* favicon added, so the tab/window is easier to identify :)

**Comment by jimklimov** [comment]
Should be fixed by several recent PRs by now.
